package com.worxbend.codeberg4s.users.social

import com.worxbend.codeberg4s.codec.PagingQuery
import com.worxbend.codeberg4s.core.CodebergRequest.{read, remove, write}
import com.worxbend.codeberg4s.core.{ApiPipeline, CodebergRequest, Exec, RetryEligibility}
import com.worxbend.codeberg4s.paging.{Page, PageParams}
import com.worxbend.codeberg4s.users.Username
import com.worxbend.codeberg4s.users.social.wire.CreateAccessTokenOptionDto
import com.worxbend.codeberg4s.{CodebergError, HttpMethod}

import scala.concurrent.Future

/** An account's personal access tokens: listing them, minting one, and revoking one.
  *
  * Reached as `client.users.tokens`. Both error rails are here (ADR-0005): the methods on this class fail the `Future`
  * with [[com.worxbend.codeberg4s.CodebergException]], and the same operations on [[UserTokenApi.attempt]] never fail
  * and return an `Either` instead. The typed rail is derived from this one by
  * [[com.worxbend.codeberg4s.core.Exec.attempt]], so the two cannot disagree about what an operation does.
  *
  * ==This is the most dangerous surface in the library, and the rules are not conventions==
  *
  * [[create]] is the only operation in codeberg4s whose success carries a working credential. Everything about how that
  * value is modelled is a defence rather than a style choice:
  *
  *   - the material comes back as [[com.worxbend.codeberg4s.auth.ApiToken]], which renders itself as `***` from
  *     `toString`, from string interpolation, and therefore from the generated `toString` of [[CreatedAccessToken]] and
  *     of anything holding one. There is no path by which printing a result prints a token;
  *   - it is returned '''once'''. `GET /users/{username}/tokens` sends the same token with its material empty, and
  *     [[AccessToken]] has no field that could hold one. A caller who does not store the value has to revoke the token
  *     and mint another;
  *   - it cannot reach a failure a caller receives, or one a telemetry sink observes.
  *     [[com.worxbend.codeberg4s.CallContext]] carries a redacted URI and never a body, and the one channel that
  *     '''would''' have carried the body — [[com.worxbend.codeberg4s.CodebergError.DecodingFailed.snippet]], which
  *     [[com.worxbend.codeberg4s.core.ApiPipeline]] fills with an excerpt of the response — is replaced by a
  *     placeholder inside the pipeline, because the decoder this endpoint uses is marked
  *     [[com.worxbend.codeberg4s.core.Decode.sensitive]]. See [[create]];
  *   - it never travels in a request. The material is generated by the instance, so no renderer in this library holds
  *     one and no request body can leak one.
  *
  * `UserTokenApiSuite` asserts each of those rather than asserting the intention.
  *
  * ==Authentication, and why the path takes a username==
  *
  * Every path here names an account explicitly. `POST` and `DELETE` need a token of their own, or basic credentials —
  * Forgejo permits minting a token with a password, which is how the first token is obtained. `docs/HAZARDS.md` §2
  * measures that the spec carries no per-operation security information, so treat the `optional` marking on the listing
  * as unverified and configure credentials.
  *
  * A token can only be managed for the account the credentials belong to, unless they are an administrator's. Asking
  * about somebody else's tokens is `403`, not an empty listing.
  *
  * ==Evidence==
  *
  * '''Derived from `spec/swagger.v1.json`, not from a captured response.''' Every endpoint here requires authentication
  * and the golden harvest was anonymous, so the field set of [[AccessToken]], the `{owner, name}` shape of a repository
  * restriction and the scope vocabulary are the spec read literally. See [[TokenScope]] for what "vocabulary" means
  * when the spec declares an `example` and no `enum`.
  *
  * ==Failures==
  *
  *   - [[com.worxbend.codeberg4s.CodebergError.Api]] with status `403` when the credentials may not manage this
  *     account's tokens, `404` when the account or the named token does not exist, `422` when a deletion is rejected,
  *     and `400` when a creation is — `docs/HAZARDS.md` §4 records Forgejo using `400` where a reader would expect
  *     `422`, and this endpoint group is one of the places it does. `401` is possible wherever credentials were
  *     required and none were sent.
  *   - [[com.worxbend.codeberg4s.CodebergError.Transport]] when nothing reached the instance.
  *   - [[com.worxbend.codeberg4s.CodebergError.DecodingFailed]] when a `2xx` payload did not match the model.
  *   - [[com.worxbend.codeberg4s.CodebergError.RetriesExhausted]] when a retryable failure outlived the policy.
  *
  * [[com.worxbend.codeberg4s.CodebergError.Validation]] is '''not''' produced by any operation here.
  *
  * @param pipeline
  *   the shared request pipeline; the only thing here that reaches the network
  */
final class UserTokenApi private[codeberg4s] (pipeline: ApiPipeline[Future])(using exec: Exec[Future]):

  /** The same operations, with failures as values instead of as a failed `Future`. */
  val attempt: UserTokenApi.Attempt = UserTokenApi.Attempt(this)

  /** Lists an account's access tokens — `GET /users/{username}/tokens`.
    *
    * '''No token material comes back.''' Forgejo sends the `sha1` field empty on every element, and
    * [[com.worxbend.codeberg4s.users.social.wire.AccessTokenDto.toDomainAt]] — the conversion this listing uses — has
    * nowhere to put one even if a release started sending it. What identifies a token to a human is
    * [[AccessToken.lastEight]].
    *
    * '''Failures.''' The group contract above; a decoding failure means an element carried no `id`, reported at `$[n]`.
    * `GET` is safe, so the call is retried under [[com.worxbend.codeberg4s.core.RetryEligibility.IdempotentOnly]].
    */
  def list(username: Username, params: PageParams): Future[Page[AccessToken]] =
    pipeline.callPage(UserTokenApi.listRequest(username, params), params)(using SocialDecoders.accessTokens)

  /** Mints an access token — `POST /users/{username}/tokens`.
    *
    * '''Read the class note before using this.''' The returned [[CreatedAccessToken.token]] is the only copy of the
    * credential that will ever exist outside the instance's database.
    *
    * A token with no scopes is created successfully and authorises nothing; see [[CreateAccessToken]]. A token confined
    * to repositories is confined to exactly those; an unconfined one reaches every repository the account can.
    *
    * '''Never retried''', under [[com.worxbend.codeberg4s.core.RetryEligibility.Never]], and this is the strongest case
    * in the library for that choice. A repeat after a lost success mints a '''second working credential''' that the
    * caller never learns the value of and therefore cannot revoke — a credential leaked into existence by a retry. It
    * would also earn a `409` or `400` on instances that reject a duplicate name, which is the harmless outcome and not
    * one to rely on.
    *
    * '''Answers `201`''' with the token and its metadata.
    *
    * ==The one place a body excerpt is thrown away==
    *
    * [[com.worxbend.codeberg4s.core.ApiPipeline]] puts a bounded excerpt of the response body into every
    * [[com.worxbend.codeberg4s.CodebergError.DecodingFailed]], which is exactly the right default and exactly wrong
    * here: the `201` body of this endpoint '''is''' a credential, so a payload that did not decode — one carrying
    * `sha1` but no `id`, say — would put a minted, working token into whatever the caller logs.
    *
    * The decoder this call passes to the pipeline is therefore marked
    * [[com.worxbend.codeberg4s.core.Decode.sensitive]], and the pipeline substitutes
    * [[com.worxbend.codeberg4s.core.ApiPipeline.redactedSnippet]] for the excerpt as it builds the failure. The `path`
    * and the reason survive untouched, so the failure is still diagnosable, and the placeholder still reports that a
    * body arrived and how many bytes it held; what is lost is the payload dump, which for this one endpoint is the part
    * nobody may see.
    *
    * '''The substitution happens inside the pipeline, and that is the point.''' Scrubbing the failure here, after the
    * call returned, would have left [[com.worxbend.codeberg4s.core.Telemetry.onError]] observing the un-scrubbed one:
    * the hook fires while the attempt is being settled, before any endpoint sees the result. A deployment that logs raw
    * telemetry errors '''and''' hits a malformed `201` on this endpoint would have recorded the token.
    *
    * '''Failures.''' The group contract above; a decoding failure means the payload carried no `id`, or no usable
    * `sha1` — and [[com.worxbend.codeberg4s.CodebergError.Validation]] never echoes a rejected value, so the reason
    * text does not carry the credential either.
    */
  def create(username: Username, command: CreateAccessToken): Future[CreatedAccessToken] =
    pipeline.call(UserTokenApi.createRequest(username, command), RetryEligibility.Never)(using
      SocialDecoders.createdAccessToken)

  /** Revokes an access token — `DELETE /users/{username}/tokens/{token}`.
    *
    * '''Whether this is retried depends on how the token was addressed''', and the difference is a real hazard rather
    * than a nicety — see [[UserTokenApi.deleteEligibility]] for the decision and [[AccessTokenRef]] for the reasoning.
    * In short: [[AccessTokenRef.ById]] names a row the instance never reuses and is retried, while
    * [[AccessTokenRef.ByName]] names something the caller can recreate and is not, because a retry after a lost success
    * could revoke a credential that was minted in between and is already in use.
    *
    * '''Answers `204` with no body''', so nothing is decoded.
    *
    * '''Failures.''' The group contract above. A `404` after a retried delete means "it is gone", not necessarily "it
    * was never there".
    */
  def delete(username: Username, token: AccessTokenRef): Future[Unit] =
    pipeline.callUnit(UserTokenApi.deleteRequest(username, token), UserTokenApi.deleteEligibility(token))

/** The requests this group issues, its typed rail, and the one retry decision it makes from an argument. */
object UserTokenApi:

  /** The stable operation id [[UserTokenApi.list]] copies into every failure's [[com.worxbend.codeberg4s.CallContext]].
    * Safe to alert on.
    */
  val ListOperation: String = "users.tokens.list"

  /** The stable operation id of [[UserTokenApi.create]]. */
  val CreateOperation: String = "users.tokens.create"

  /** The stable operation id of [[UserTokenApi.delete]]. */
  val DeleteOperation: String = "users.tokens.delete"

  /** Whether revoking a token addressed by `token` may be attempted again.
    *
    * Exposed rather than hidden, because it is the one place in this group where a retry decision depends on a value
    * the caller chose, and a caller reasoning about what a lost response could cost should be able to read the answer
    * rather than infer it.
    *
    *   - [[AccessTokenRef.ById]] gives [[com.worxbend.codeberg4s.core.RetryEligibility.AlwaysRetry]]. The request names
    *     one instance-wide row identifier the server never reuses, so every attempt addresses the same token or nothing
    *     at all, nothing is created, and the end state after N attempts is the end state after one.
    *   - [[AccessTokenRef.ByName]] gives [[com.worxbend.codeberg4s.core.RetryEligibility.Never]]. A name is reusable: a
    *     token of the same name can exist again between two attempts, and a retry would then revoke a working
    *     credential the caller did not name. That is the failure mode the whole per-endpoint retry rule exists to
    *     prevent, and it is worse here than anywhere else in the library because the damage is silent — the revoked
    *     token simply starts answering `401` somewhere else.
    */
  def deleteEligibility(token: AccessTokenRef): RetryEligibility =
    token match
      case AccessTokenRef.ById(_)   => RetryEligibility.AlwaysRetry
      case AccessTokenRef.ByName(_) => RetryEligibility.Never

  /** The typed rail of [[UserTokenApi]]: every operation, with [[com.worxbend.codeberg4s.CodebergError]] as a value.
    *
    * Obtained as `client.users.tokens.attempt`. Each method is the convenience-rail method with its failure channel
    * materialised, so an operation exists on exactly one of the rails only if it is missing from both.
    */
  final class Attempt private[codeberg4s] (rail: UserTokenApi)(using exec: Exec[Future]):

    /** [[UserTokenApi.list]] with its failure as a value. The returned `Future` never fails with a
      * [[com.worxbend.codeberg4s.CodebergException]].
      */
    def list(username: Username, params: PageParams): Future[Either[CodebergError, Page[AccessToken]]] =
      exec.attempt(rail.list(username, params))

    /** [[UserTokenApi.create]] with its failure as a value.
      *
      * A `Left` never carries the credential: there is no credential on a failed creation, and
      * [[com.worxbend.codeberg4s.CodebergError]] has nowhere to put one in any case.
      */
    def create(
        username: Username,
        command: CreateAccessToken,
    ): Future[Either[CodebergError, CreatedAccessToken]] =
      exec.attempt(rail.create(username, command))

    /** [[UserTokenApi.delete]] with its failure as a value. */
    def delete(username: Username, token: AccessTokenRef): Future[Either[CodebergError, Unit]] =
      exec.attempt(rail.delete(username, token))

  private def listRequest(username: Username, params: PageParams): CodebergRequest =
    read(ListOperation, tokensPath(username), PagingQuery.window(params))

  private def createRequest(username: Username, command: CreateAccessToken): CodebergRequest =
    write(CreateOperation, HttpMethod.Post, tokensPath(username), CreateAccessTokenOptionDto.render(command))

  private def deleteRequest(username: Username, token: AccessTokenRef): CodebergRequest =
    remove(DeleteOperation, tokensPath(username) :+ token.pathSegment)

  private def tokensPath(username: Username): List[String] =
    List("users", username.value, "tokens")
